# Cuboids
#FREEHC.PL (C) 2023


database:
  # Database type (MySQL, H2)
    type: H2
    MySQL:
      # MySQL database host
      host: localhost
      # MySQL database port
      port: 3306
      # MySQL database name
      database: fhcuboids
      # MySQL database username
      username: root
      # MySQL database password
      password: ""
    H2:
      # H2 database file name
      file: database

Debug: false


#Allowed commands on cuboid for non-added players
AllowedCommandsOnCuboid: ["/home", "/spawn", "/warp", "/tpa", "/msg", "/r", "/reply", "/cuboid"]

CuboidLevels: [
  {
    size: 30, #The number must be even for the boundary to be drawn from the cuboid centre
    item: "SPONGE",
    groups: ["default", "vip"],
    worlds: ["world"],
    pvp: true,
    price: 0,
    crafting: [ COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, DIRT, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE ]
  },
  {
    size: 60,
    item: "SPONGE",
    groups: ["default", "vip"],
    worlds: ["world"],
    pvp: true,
    price: 12500,
    crafting: [COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, IRON_BLOCK, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE]
  },
  {
    size: 20,
    item: "NETHERITE_BLOCK",
    groups: ["default", "vip"],
    worlds: ["world_nether"],
    pvp: true,
    price: 12500,
    crafting: [COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, IRON_BLOCK, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE]
  }
]

CuboidGroups: [
  {
    name: "default", #Permission: FHCuboids.groups.default
    priority: 0,
    limit: 1
  },
  {
    name: "vip",
    priority: 1,
    limit: 2
  }
]

PrefixedText: "&aFreeHC.pl &c>> &r"

PrefixedBulletText: "&c>> &r"

CuboidBlock: SPONGE

CuboidBlockName: "&aCuboid"