# Cuboids
#FREEHC.PL (C) 2023


database:
  # Database type (MySQL, H2)
    type: MySQL
    MySQL:
      # MySQL database host
      host: localhost
      # MySQL database port
      port: 3306
      # MySQL database name
      database: fhcuboids
      # MySQL database username
      username: root
      # MySQL database password
      password: ""
    H2:
      # H2 database file name
      file: database

Debug: false

CuboidWorldName: world

#Allowed commands on cuboid for non-added players
AllowedCommandsOnCuboid: ["/home", "/spawn", "/warp", "/tpa", "/msg", "/r", "/reply", "/cuboid"]

CuboidLevels: [
  {
    size: 30, #The number must be even for the boundary to be drawn from the cuboid centre
    item: "SPONGE",
    price: 0,
    crafting: [ COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, DIRT, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE ]
  },
  {
    size: 60,
    item: "SPONGE",
    price: 12500,
    crafting: [COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, IRON_BLOCK, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE]
  },
  {
    size: 80,
    item: "SPONGE",
    price: 37500,
    crafting: [ COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, GOLD_BLOCK, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE ]
  },
  {
    size: 100,
    item: "SPONGE",
    price: 75000,
    crafting: [ COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, DIAMOND_BLOCK, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE ]
  },
  {
    size: 120,
    item: "SPONGE",
    price: 125000,
    crafting: [ COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE, NETHERITE_BLOCK, COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE ]
  },
  {
    size: 140,
    item: "SPONGE",
    price: 187500,
    crafting: [ IRON_BLOCK, IRON_BLOCK, IRON_BLOCK, IRON_BLOCK, NETHERITE_BLOCK, IRON_BLOCK, IRON_BLOCK, IRON_BLOCK, IRON_BLOCK ]
  },
  {
    size: 160,
    item: "SPONGE",
    price: 262500,
    crafting: [ GOLD_BLOCK, GOLD_BLOCK, GOLD_BLOCK, GOLD_BLOCK, NETHERITE_BLOCK, GOLD_BLOCK, GOLD_BLOCK, GOLD_BLOCK, GOLD_BLOCK ]
  },
  {
    size: 180,
    item: "SPONGE",
    price: 350000,
    crafting: [ DIAMOND_BLOCK, DIAMOND_BLOCK, DIAMOND_BLOCK, DIAMOND_BLOCK, NETHERITE_BLOCK, DIAMOND_BLOCK, DIAMOND_BLOCK, DIAMOND_BLOCK, DIAMOND_BLOCK ]
  },
  {
    size: 200,
    item: "SPONGE",
    price: 450000,
    crafting: [ NETHERITE_BLOCK, NETHERITE_BLOCK, NETHERITE_BLOCK, NETHERITE_BLOCK, ELYTRA, NETHERITE_BLOCK, NETHERITE_BLOCK, NETHERITE_BLOCK, NETHERITE_BLOCK ]
  }
]

PrefixedText: "&aFreeHC.pl &c>> &r"

PrefixedBulletText: "&c>> &r"

CuboidBlock: SPONGE

CuboidBlockName: "&aCuboid"