main: pl.freehc.fhcuboids.App
name: FHCuboids
version: 3.0
softdepend: [Dynmap]
api-version: 1.19
depend: [Vault]
commands:
   cuboid:
      description: komendy zwiazane z cuboidem
      usage: /<komenda>
      permission: FHCuboids.use
      permission-message: Nie masz uprawnień