name: Build and Publish Artifact
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'

      - name: Build with Gradle
        run: ./gradlew shadowJar --no-daemon
      - name: version
        run: echo "::set-output name=version::$(./gradlew -q printVersion)"
        id: version
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: shadowJar
          path: build/libs/*.jar
