name: Build and Publish Artifact
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew shadowJar --no-daemon

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: shadowJar
          path: build/libs/*.jar
